[page]
margin_top = "1.25cm"
margin_bottom = "1.25cm"
margin_left = "1.6cm"
margin_right = "1.6cm"

[global]
lang = "en"
show_furigana = true
font_size = 10.5
heading_size = 14
subheading_size = 10.5
list_size = 10
font_content = "Spectral"
font_content_cjk = "Noto Serif SC"
font_title = "Rethink Sans"
font_title_cjk = "IBM Plex Sans SC"
name_font = "Noto Serif SC"
font_mono = "Inconsolata"
font_math = "New Computer Modern Math"

[header]
name_size = 22
original_name_size = 17
contact_size = 11

[footer]
show_name = true
# text = "Full CV: #link(\"https://keyzh.pages.dev\")[`keyzh.pages.dev`]"
show_updated = true
updated_prefix = "Last Updated:"
show_page = true
page_format = "1 of 1"

[sections.default]
font_title = "Rethink Sans"
font_content = "Spectral"
# heading_gap = "0.6em"
# section_gap = "0pt"

[sections.skills]
font_title = "IBM Plex Sans"
text_size = 10
