[package]
name = "xyndrome"
version = "0.1.0"
entrypoint = "xyndrome/lib.typ"
authors = ["Xeraphinite"]
categories = ["cv"]
license = "MIT"
description = "Xyndrome: A modern, clean, and customizable CV template for Typst"
repository = "https://github.com/Xeraphinite/xyndrome-cv"
keywords = ["cv", "resume", "template"]

[template]
entrypoint = "main.typ"
path = "xyndrome"
thumbnail = "thumbnail.png"