[page]
margin_top = "1.5cm"
margin_bottom = "2cm"
margin_left = "1.8cm"
margin_right = "1.8cm"

[global]
lang = "zh"
show_furigana = false
font_content = "MiSans"
font_title = "Noto Serif SC"
name_font = "Noto Serif SC"
font_mono = "Maple Mono"
font_math = "New Computer Modern Math"
font_size = 10.5
heading_size = 13
subheading_size = 10.5
list_size = 9.5
section_gap = "0.1cm"

[header]
alignment = "left"
original_name_size = 22
job_intent_size = 12
contact_size = 10
show_avatar = true
avatar_size = "1.8cm"
avatar_path = "../assets/avatar.png"

[footer]
show_name = false
show_updated = false
show_page = true
page_format = "1 / 1"

[sections.publications]
font_content = "Spectral"
text_size = 10

[sections.skills]
font_content = "MiSans"

[sections.artifacts]
font_content = "MiSans"
