[page]
margin_top = "1cm"
margin_bottom = "1.25cm"
margin_left = "1.6cm"
margin_right = "1.6cm"

[global]
lang = "en"
show_furigana = false
font_size = 10
heading_size = 13
subheading_size = 10.5
list_size = 9
font_content = "MiSans"
font_title = "Noto Serif SC"
name_font = "Noto Serif SC"
font_mono = "Maple Mono"
font_math = "New Computer Modern Math"

[header]
alignment = "left"
original_name_size = 20
job_intent_size = 10
contact_size = 9
show_avatar = true
avatar_size = "1.8cm"
avatar_path = "../assets/avatar.png"

[footer]
show_name = false
show_updated = false
show_page = true
page_format = "1 / 1"

[sections.publications]
font_content = "Spectral"
text_size = 10

[sections.skills]
font_content = "MiSans"
text_size = 9.5